import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Emily's Fucking Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <section >
          <div><h3>Home</h3></div>
          <div><h3>Music</h3></div>
          <div><h3>Video</h3></div>
          <div><h3>Projects</h3></div>
        </section>
        {children}
        </body>
    </html>
  );
}
